/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javahelp;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Formatter;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.*;
import java.net.*;

/**
 *
 * @author kzaiter
 */
public class Tutor extends javax.swing.JFrame {
    public String dpath = "/Users/kzaiter/NetBeansProjects/Help/src/javahelp/";
    /**
     * Creates new form Helper
     */
    public Tutor() {    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        collectBut = new javax.swing.JButton();
        ifbut = new javax.swing.JButton();
        switchstatebut = new javax.swing.JButton();
        whilelp = new javax.swing.JButton();
        forlp = new javax.swing.JButton();
        dwile = new javax.swing.JButton();
        araybut = new javax.swing.JButton();
        nestif = new javax.swing.JButton();
        tastrngbut = new javax.swing.JButton();
        enumBut = new javax.swing.JButton();
        commonstringmethbut = new javax.swing.JButton();
        aLButton = new javax.swing.JButton();
        llbut = new javax.swing.JButton();
        genRetBut = new javax.swing.JButton();
        genMBut = new javax.swing.JButton();
        oVBut = new javax.swing.JButton();
        hashBut = new javax.swing.JButton();
        queBut = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        recurBut = new javax.swing.JButton();
        trcabut = new javax.swing.JButton();
        sppBut = new javax.swing.JButton();
        atlBut = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        mouseABut = new javax.swing.JButton();
        fileBut = new javax.swing.JButton();
        qualBut = new javax.swing.JButton();
        meventsBut = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        multiDBut = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        ranBut = new javax.swing.JButton();
        enhancedbut = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        readMeBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("<|_2:32 Tutor_|>");
        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 1300));
        jPanel1.setLayout(null);

        collectBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/collections.jpg"))); // NOI18N
        collectBut.setToolTipText("");
        collectBut.setBorderPainted(false);
        collectBut.setMaximumSize(new java.awt.Dimension(160, 40));
        collectBut.setMinimumSize(new java.awt.Dimension(160, 40));
        collectBut.setPreferredSize(new java.awt.Dimension(160, 40));
        collectBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/collectionsf.jpg"))); // NOI18N
        collectBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectButActionPerformed(evt);
            }
        });
        jPanel1.add(collectBut);
        collectBut.setBounds(230, 370, 160, 40);

        ifbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/ifstatement.jpg"))); // NOI18N
        ifbut.setBorderPainted(false);
        ifbut.setMaximumSize(new java.awt.Dimension(160, 40));
        ifbut.setMinimumSize(new java.awt.Dimension(160, 40));
        ifbut.setPreferredSize(new java.awt.Dimension(160, 40));
        ifbut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/ifstatementf.jpg"))); // NOI18N
        ifbut.setSize(new java.awt.Dimension(160, 40));
        ifbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifbutActionPerformed(evt);
            }
        });
        jPanel1.add(ifbut);
        ifbut.setBounds(40, 170, 160, 40);

        switchstatebut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/switchstate.jpg"))); // NOI18N
        switchstatebut.setToolTipText("");
        switchstatebut.setBorderPainted(false);
        switchstatebut.setPreferredSize(new java.awt.Dimension(160, 40));
        switchstatebut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/switchstatef.jpg"))); // NOI18N
        switchstatebut.setSize(new java.awt.Dimension(160, 40));
        switchstatebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchstatebutActionPerformed(evt);
            }
        });
        jPanel1.add(switchstatebut);
        switchstatebut.setBounds(40, 410, 160, 40);

        whilelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/whileLoop.jpg"))); // NOI18N
        whilelp.setBorderPainted(false);
        whilelp.setMaximumSize(new java.awt.Dimension(160, 40));
        whilelp.setMinimumSize(new java.awt.Dimension(160, 40));
        whilelp.setPreferredSize(new java.awt.Dimension(160, 40));
        whilelp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/whileLoopf.jpg"))); // NOI18N
        whilelp.setSize(new java.awt.Dimension(160, 40));
        whilelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whilelpActionPerformed(evt);
            }
        });
        jPanel1.add(whilelp);
        whilelp.setBounds(40, 330, 160, 40);

        forlp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/forLoop.jpg"))); // NOI18N
        forlp.setBorderPainted(false);
        forlp.setMaximumSize(new java.awt.Dimension(160, 40));
        forlp.setMinimumSize(new java.awt.Dimension(160, 40));
        forlp.setPreferredSize(new java.awt.Dimension(160, 40));
        forlp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/forLoopf.jpg"))); // NOI18N
        forlp.setSize(new java.awt.Dimension(160, 40));
        forlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forlpActionPerformed(evt);
            }
        });
        jPanel1.add(forlp);
        forlp.setBounds(40, 250, 160, 40);

        dwile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/doWhile.jpg"))); // NOI18N
        dwile.setBorderPainted(false);
        dwile.setMaximumSize(new java.awt.Dimension(160, 40));
        dwile.setMinimumSize(new java.awt.Dimension(160, 40));
        dwile.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/doWhilef.jpg"))); // NOI18N
        dwile.setSize(new java.awt.Dimension(160, 40));
        dwile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dwileActionPerformed(evt);
            }
        });
        jPanel1.add(dwile);
        dwile.setBounds(40, 370, 160, 40);

        araybut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/array.jpg"))); // NOI18N
        araybut.setBorderPainted(false);
        araybut.setMaximumSize(new java.awt.Dimension(160, 40));
        araybut.setMinimumSize(new java.awt.Dimension(160, 40));
        araybut.setPreferredSize(new java.awt.Dimension(160, 40));
        araybut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/arrayf.jpg"))); // NOI18N
        araybut.setSize(new java.awt.Dimension(160, 40));
        araybut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araybutActionPerformed(evt);
            }
        });
        jPanel1.add(araybut);
        araybut.setBounds(40, 450, 160, 40);

        nestif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/nested.jpg"))); // NOI18N
        nestif.setBorderPainted(false);
        nestif.setMaximumSize(new java.awt.Dimension(160, 40));
        nestif.setMinimumSize(new java.awt.Dimension(160, 40));
        nestif.setPreferredSize(new java.awt.Dimension(160, 40));
        nestif.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/nestedf.jpg"))); // NOI18N
        nestif.setSize(new java.awt.Dimension(160, 40));
        nestif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nestifActionPerformed(evt);
            }
        });
        jPanel1.add(nestif);
        nestif.setBounds(40, 210, 160, 40);

        tastrngbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/toString.jpg"))); // NOI18N
        tastrngbut.setBorderPainted(false);
        tastrngbut.setMaximumSize(new java.awt.Dimension(160, 40));
        tastrngbut.setMinimumSize(new java.awt.Dimension(160, 40));
        tastrngbut.setPreferredSize(new java.awt.Dimension(160, 40));
        tastrngbut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/toStringf.jpg"))); // NOI18N
        tastrngbut.setSize(new java.awt.Dimension(160, 40));
        tastrngbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tastrngbutActionPerformed(evt);
            }
        });
        jPanel1.add(tastrngbut);
        tastrngbut.setBounds(230, 290, 160, 40);

        enumBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/enumeration.jpg"))); // NOI18N
        enumBut.setToolTipText("");
        enumBut.setBorderPainted(false);
        enumBut.setMaximumSize(new java.awt.Dimension(160, 40));
        enumBut.setMinimumSize(new java.awt.Dimension(160, 40));
        enumBut.setPreferredSize(new java.awt.Dimension(160, 40));
        enumBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/enumerationf.jpg"))); // NOI18N
        enumBut.setSize(new java.awt.Dimension(160, 40));
        enumBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enumButActionPerformed(evt);
            }
        });
        jPanel1.add(enumBut);
        enumBut.setBounds(420, 130, 160, 40);

        commonstringmethbut.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        commonstringmethbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/commonstring.jpg"))); // NOI18N
        commonstringmethbut.setBorderPainted(false);
        commonstringmethbut.setMinimumSize(new java.awt.Dimension(160, 40));
        commonstringmethbut.setPreferredSize(new java.awt.Dimension(160, 40));
        commonstringmethbut.setRequestFocusEnabled(false);
        commonstringmethbut.setRolloverEnabled(true);
        commonstringmethbut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/commonstrinf.jpg"))); // NOI18N
        commonstringmethbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonstringmethbutActionPerformed(evt);
            }
        });
        jPanel1.add(commonstringmethbut);
        commonstringmethbut.setBounds(40, 130, 160, 40);

        aLButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/arraylst.jpg"))); // NOI18N
        aLButton.setBorderPainted(false);
        aLButton.setMaximumSize(new java.awt.Dimension(160, 40));
        aLButton.setMinimumSize(new java.awt.Dimension(160, 40));
        aLButton.setPreferredSize(new java.awt.Dimension(160, 40));
        aLButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/arraylstf.jpg"))); // NOI18N
        aLButton.setSize(new java.awt.Dimension(160, 40));
        aLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aLButtonActionPerformed(evt);
            }
        });
        jPanel1.add(aLButton);
        aLButton.setBounds(230, 170, 160, 40);

        llbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/linkedList.jpg"))); // NOI18N
        llbut.setBorderPainted(false);
        llbut.setMaximumSize(new java.awt.Dimension(160, 40));
        llbut.setMinimumSize(new java.awt.Dimension(160, 40));
        llbut.setPreferredSize(new java.awt.Dimension(160, 40));
        llbut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/linkedListf.jpg"))); // NOI18N
        llbut.setSize(new java.awt.Dimension(160, 40));
        llbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llbutActionPerformed(evt);
            }
        });
        jPanel1.add(llbut);
        llbut.setBounds(230, 250, 160, 40);

        genRetBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/genreturn.jpg"))); // NOI18N
        genRetBut.setBorderPainted(false);
        genRetBut.setMaximumSize(new java.awt.Dimension(160, 40));
        genRetBut.setMinimumSize(new java.awt.Dimension(160, 40));
        genRetBut.setPreferredSize(new java.awt.Dimension(160, 40));
        genRetBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/genreturnf.jpg"))); // NOI18N
        genRetBut.setSize(new java.awt.Dimension(160, 40));
        genRetBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genRetButActionPerformed(evt);
            }
        });
        jPanel1.add(genRetBut);
        genRetBut.setBounds(230, 490, 160, 40);

        genMBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/genmethod.jpg"))); // NOI18N
        genMBut.setBorderPainted(false);
        genMBut.setMaximumSize(new java.awt.Dimension(160, 40));
        genMBut.setMinimumSize(new java.awt.Dimension(160, 40));
        genMBut.setPreferredSize(new java.awt.Dimension(160, 40));
        genMBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/genmethodf.jpg"))); // NOI18N
        genMBut.setSize(new java.awt.Dimension(160, 40));
        genMBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genMButActionPerformed(evt);
            }
        });
        jPanel1.add(genMBut);
        genMBut.setBounds(230, 450, 160, 40);

        oVBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/overloaded.jpg"))); // NOI18N
        oVBut.setBorderPainted(false);
        oVBut.setMaximumSize(new java.awt.Dimension(160, 40));
        oVBut.setMinimumSize(new java.awt.Dimension(160, 40));
        oVBut.setPreferredSize(new java.awt.Dimension(160, 40));
        oVBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/overloadedf.jpg"))); // NOI18N
        oVBut.setSize(new java.awt.Dimension(160, 40));
        oVBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oVButActionPerformed(evt);
            }
        });
        jPanel1.add(oVBut);
        oVBut.setBounds(230, 410, 160, 40);

        hashBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/hashset.jpg"))); // NOI18N
        hashBut.setBorderPainted(false);
        hashBut.setMaximumSize(new java.awt.Dimension(160, 40));
        hashBut.setMinimumSize(new java.awt.Dimension(160, 40));
        hashBut.setPreferredSize(new java.awt.Dimension(160, 40));
        hashBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/hashsetf.jpg"))); // NOI18N
        hashBut.setSize(new java.awt.Dimension(160, 40));
        hashBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashButActionPerformed(evt);
            }
        });
        jPanel1.add(hashBut);
        hashBut.setBounds(420, 330, 160, 40);

        queBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/queue.jpg"))); // NOI18N
        queBut.setBorderPainted(false);
        queBut.setMaximumSize(new java.awt.Dimension(160, 40));
        queBut.setMinimumSize(new java.awt.Dimension(160, 40));
        queBut.setPreferredSize(new java.awt.Dimension(160, 40));
        queBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/queuef.jpg"))); // NOI18N
        queBut.setSize(new java.awt.Dimension(160, 40));
        queBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queButActionPerformed(evt);
            }
        });
        jPanel1.add(queBut);
        queBut.setBounds(420, 290, 160, 40);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/multiselect.jpg"))); // NOI18N
        jButton22.setBorderPainted(false);
        jButton22.setMaximumSize(new java.awt.Dimension(160, 40));
        jButton22.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton22.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton22.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/multiselectf copy.jpg"))); // NOI18N
        jButton22.setSize(new java.awt.Dimension(160, 40));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22);
        jButton22.setBounds(610, 290, 160, 40);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/jlist.jpg"))); // NOI18N
        jButton23.setBorderPainted(false);
        jButton23.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton23.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton23.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/jlistf.jpg"))); // NOI18N
        jButton23.setSize(new java.awt.Dimension(160, 40));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);
        jButton23.setBounds(610, 250, 160, 40);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/jradio.jpg"))); // NOI18N
        jButton24.setBorderPainted(false);
        jButton24.setMaximumSize(new java.awt.Dimension(160, 40));
        jButton24.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton24.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton24.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/jradiof.jpg"))); // NOI18N
        jButton24.setSize(new java.awt.Dimension(160, 40));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton24);
        jButton24.setBounds(610, 170, 160, 40);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/jcombo.jpg"))); // NOI18N
        jButton25.setBorderPainted(false);
        jButton25.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton25.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton25.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/jcombof.jpg"))); // NOI18N
        jButton25.setSize(new java.awt.Dimension(160, 40));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton25);
        jButton25.setBounds(610, 330, 160, 40);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/jcolorchoose.jpg"))); // NOI18N
        jButton26.setBorderPainted(false);
        jButton26.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton26.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/jcolorchoosef.jpg"))); // NOI18N
        jButton26.setSize(new java.awt.Dimension(160, 40));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton26);
        jButton26.setBounds(610, 370, 160, 40);

        recurBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/Recursion.jpg"))); // NOI18N
        recurBut.setToolTipText("");
        recurBut.setBorderPainted(false);
        recurBut.setMaximumSize(new java.awt.Dimension(160, 40));
        recurBut.setMinimumSize(new java.awt.Dimension(160, 40));
        recurBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/recursionf.jpg"))); // NOI18N
        recurBut.setSize(new java.awt.Dimension(160, 40));
        recurBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recurButActionPerformed(evt);
            }
        });
        jPanel1.add(recurBut);
        recurBut.setBounds(420, 170, 160, 40);

        trcabut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/trycatch.jpg"))); // NOI18N
        trcabut.setBorderPainted(false);
        trcabut.setMinimumSize(new java.awt.Dimension(160, 40));
        trcabut.setPreferredSize(new java.awt.Dimension(160, 40));
        trcabut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/trycatchf.jpg"))); // NOI18N
        trcabut.setSize(new java.awt.Dimension(160, 40));
        trcabut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trcabutActionPerformed(evt);
            }
        });
        jPanel1.add(trcabut);
        trcabut.setBounds(230, 330, 160, 40);

        sppBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/stackpush.jpg"))); // NOI18N
        sppBut.setBorderPainted(false);
        sppBut.setMaximumSize(new java.awt.Dimension(160, 40));
        sppBut.setMinimumSize(new java.awt.Dimension(160, 40));
        sppBut.setPreferredSize(new java.awt.Dimension(160, 40));
        sppBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/stackpushf.jpg"))); // NOI18N
        sppBut.setSize(new java.awt.Dimension(160, 40));
        sppBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sppButActionPerformed(evt);
            }
        });
        jPanel1.add(sppBut);
        sppBut.setBounds(420, 370, 160, 40);

        atlBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/array2list.jpg"))); // NOI18N
        atlBut.setBorderPainted(false);
        atlBut.setMinimumSize(new java.awt.Dimension(160, 40));
        atlBut.setPreferredSize(new java.awt.Dimension(160, 40));
        atlBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/array2listf.jpg"))); // NOI18N
        atlBut.setSize(new java.awt.Dimension(160, 40));
        atlBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atlButActionPerformed(evt);
            }
        });
        jPanel1.add(atlBut);
        atlBut.setBounds(230, 210, 160, 40);

        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/jframe.jpg"))); // NOI18N
        jButton31.setBorderPainted(false);
        jButton31.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton31.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton31.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/jframef.jpg"))); // NOI18N
        jButton31.setSize(new java.awt.Dimension(160, 40));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton31);
        jButton31.setBounds(610, 130, 160, 40);

        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/sum2.jpg"))); // NOI18N
        jButton32.setBorderPainted(false);
        jButton32.setMaximumSize(new java.awt.Dimension(160, 40));
        jButton32.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton32.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton32.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/guisumf.jpg"))); // NOI18N
        jButton32.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/guisumf.jpg"))); // NOI18N
        jButton32.setSize(new java.awt.Dimension(160, 40));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton32);
        jButton32.setBounds(610, 450, 160, 40);

        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/guievent.jpg"))); // NOI18N
        jButton33.setBorderPainted(false);
        jButton33.setMaximumSize(new java.awt.Dimension(160, 40));
        jButton33.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton33.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton33.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/guieventf.jpg"))); // NOI18N
        jButton33.setSize(new java.awt.Dimension(160, 40));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton33);
        jButton33.setBounds(610, 410, 160, 40);

        mouseABut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/mouseadapt.jpg"))); // NOI18N
        mouseABut.setBorderPainted(false);
        mouseABut.setMaximumSize(new java.awt.Dimension(160, 40));
        mouseABut.setMinimumSize(new java.awt.Dimension(160, 40));
        mouseABut.setPreferredSize(new java.awt.Dimension(160, 40));
        mouseABut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/mouseadaptf.jpg"))); // NOI18N
        mouseABut.setSize(new java.awt.Dimension(160, 40));
        mouseABut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouseAButActionPerformed(evt);
            }
        });
        jPanel1.add(mouseABut);
        mouseABut.setBounds(420, 450, 160, 40);

        fileBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/fileio.jpg"))); // NOI18N
        fileBut.setBorderPainted(false);
        fileBut.setMaximumSize(new java.awt.Dimension(160, 40));
        fileBut.setMinimumSize(new java.awt.Dimension(160, 40));
        fileBut.setPreferredSize(new java.awt.Dimension(160, 40));
        fileBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/filef.jpg"))); // NOI18N
        fileBut.setSize(new java.awt.Dimension(160, 40));
        fileBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButActionPerformed(evt);
            }
        });
        jPanel1.add(fileBut);
        fileBut.setBounds(420, 410, 160, 40);

        qualBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/equalsMethod.jpg"))); // NOI18N
        qualBut.setBorderPainted(false);
        qualBut.setPreferredSize(new java.awt.Dimension(160, 40));
        qualBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/equalsMethodf.jpg"))); // NOI18N
        qualBut.setSize(new java.awt.Dimension(160, 40));
        qualBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualButActionPerformed(evt);
            }
        });
        jPanel1.add(qualBut);
        qualBut.setBounds(420, 250, 160, 40);

        meventsBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/mouseEvents.jpg"))); // NOI18N
        meventsBut.setBorderPainted(false);
        meventsBut.setMaximumSize(new java.awt.Dimension(160, 40));
        meventsBut.setMinimumSize(new java.awt.Dimension(160, 40));
        meventsBut.setPreferredSize(new java.awt.Dimension(160, 40));
        meventsBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/mouseeventf.jpg"))); // NOI18N
        meventsBut.setSize(new java.awt.Dimension(160, 40));
        meventsBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meventsButActionPerformed(evt);
            }
        });
        jPanel1.add(meventsBut);
        meventsBut.setBounds(420, 490, 160, 40);

        jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/jcheck.jpg"))); // NOI18N
        jButton40.setBorderPainted(false);
        jButton40.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton40.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton40.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/jcheckf.jpg"))); // NOI18N
        jButton40.setSize(new java.awt.Dimension(160, 40));
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton40);
        jButton40.setBounds(610, 210, 160, 40);

        multiDBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/mdarray.jpg"))); // NOI18N
        multiDBut.setBorderPainted(false);
        multiDBut.setMaximumSize(new java.awt.Dimension(160, 40));
        multiDBut.setMinimumSize(new java.awt.Dimension(160, 40));
        multiDBut.setPreferredSize(new java.awt.Dimension(160, 40));
        multiDBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/mdarrayf.jpg"))); // NOI18N
        multiDBut.setSize(new java.awt.Dimension(160, 40));
        multiDBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiDButActionPerformed(evt);
            }
        });
        jPanel1.add(multiDBut);
        multiDBut.setBounds(230, 130, 160, 40);

        jButton43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/arraytable.jpg"))); // NOI18N
        jButton43.setBorderPainted(false);
        jButton43.setMaximumSize(new java.awt.Dimension(160, 40));
        jButton43.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton43.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton43.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/arraytablef.jpg"))); // NOI18N
        jButton43.setSize(new java.awt.Dimension(160, 40));
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton43);
        jButton43.setBounds(40, 490, 160, 40);

        ranBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/random.jpg"))); // NOI18N
        ranBut.setBorderPainted(false);
        ranBut.setMaximumSize(new java.awt.Dimension(160, 40));
        ranBut.setMinimumSize(new java.awt.Dimension(160, 40));
        ranBut.setPreferredSize(new java.awt.Dimension(160, 40));
        ranBut.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/randomf.jpg"))); // NOI18N
        ranBut.setSize(new java.awt.Dimension(160, 40));
        ranBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ranButActionPerformed(evt);
            }
        });
        jPanel1.add(ranBut);
        ranBut.setBounds(420, 210, 160, 40);

        enhancedbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/enhancedfor.jpg"))); // NOI18N
        enhancedbut.setBorderPainted(false);
        enhancedbut.setMaximumSize(new java.awt.Dimension(160, 40));
        enhancedbut.setMinimumSize(new java.awt.Dimension(160, 40));
        enhancedbut.setPreferredSize(new java.awt.Dimension(160, 40));
        enhancedbut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/enhancedforf.jpg"))); // NOI18N
        enhancedbut.setSize(new java.awt.Dimension(160, 40));
        enhancedbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enhancedbutActionPerformed(evt);
            }
        });
        jPanel1.add(enhancedbut);
        enhancedbut.setBounds(40, 290, 160, 40);

        jButton48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/imserver.jpg"))); // NOI18N
        jButton48.setBorderPainted(false);
        jButton48.setMaximumSize(new java.awt.Dimension(160, 40));
        jButton48.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton48.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton48.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/imserverf.jpg"))); // NOI18N
        jButton48.setSize(new java.awt.Dimension(160, 40));
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton48);
        jButton48.setBounds(800, 210, 160, 40);

        jButton49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/textEdit.jpg"))); // NOI18N
        jButton49.setBorderPainted(false);
        jButton49.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton49.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/texteditf.jpg"))); // NOI18N
        jButton49.setSize(new java.awt.Dimension(160, 40));
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton49);
        jButton49.setBounds(800, 170, 160, 40);

        jButton53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/threads.jpg"))); // NOI18N
        jButton53.setBorderPainted(false);
        jButton53.setMaximumSize(new java.awt.Dimension(160, 40));
        jButton53.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton53.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton53.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/threadsf.jpg"))); // NOI18N
        jButton53.setSize(new java.awt.Dimension(160, 40));
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton53);
        jButton53.setBounds(610, 490, 160, 40);

        jButton51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/textbook.jpg"))); // NOI18N
        jButton51.setBorderPainted(false);
        jButton51.setMaximumSize(new java.awt.Dimension(160, 40));
        jButton51.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton51.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton51.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/textbookf.jpg"))); // NOI18N
        jButton51.setSize(new java.awt.Dimension(160, 40));
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton51);
        jButton51.setBounds(800, 290, 160, 40);

        jButton54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/talktutor.jpg"))); // NOI18N
        jButton54.setBorderPainted(false);
        jButton54.setMaximumSize(new java.awt.Dimension(160, 160));
        jButton54.setMinimumSize(new java.awt.Dimension(160, 160));
        jButton54.setPreferredSize(new java.awt.Dimension(160, 160));
        jButton54.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/talktutorf.jpg"))); // NOI18N
        jButton54.setSize(new java.awt.Dimension(160, 120));
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton54);
        jButton54.setBounds(800, 390, 160, 120);

        jButton55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/imclient.jpg"))); // NOI18N
        jButton55.setBorderPainted(false);
        jButton55.setMaximumSize(new java.awt.Dimension(160, 40));
        jButton55.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton55.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton55.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/imclientf.jpg"))); // NOI18N
        jButton55.setSize(new java.awt.Dimension(160, 40));
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton55);
        jButton55.setBounds(800, 250, 160, 40);

        jButton59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/webbrowse.jpg"))); // NOI18N
        jButton59.setBorderPainted(false);
        jButton59.setMaximumSize(new java.awt.Dimension(160, 40));
        jButton59.setMinimumSize(new java.awt.Dimension(160, 40));
        jButton59.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton59.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/webbrowsef.jpg"))); // NOI18N
        jButton59.setSize(new java.awt.Dimension(160, 40));
        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton59);
        jButton59.setBounds(800, 130, 160, 40);

        readMeBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/readmew.jpg"))); // NOI18N
        readMeBut.setBorderPainted(false);
        readMeBut.setMaximumSize(new java.awt.Dimension(160, 40));
        readMeBut.setMinimumSize(new java.awt.Dimension(160, 40));
        readMeBut.setPreferredSize(new java.awt.Dimension(160, 40));
        readMeBut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/readme.jpg"))); // NOI18N
        readMeBut.setSize(new java.awt.Dimension(160, 40));
        readMeBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readMeButActionPerformed(evt);
            }
        });
        jPanel1.add(readMeBut);
        readMeBut.setBounds(800, 330, 160, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/topBannerv5.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-20, 0, 1040, 103);
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javahelp/imageResources/mainBGv7.jpg"))); // NOI18N
        jLabel2.setSize(new java.awt.Dimension(1000, 550));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 100, 1000, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void collectButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectButActionPerformed
        System.out.println("");
        CollectionsMethodString cms = new CollectionsMethodString();
        CollectionsMethodsChar cmc = new CollectionsMethodsChar();
        CollectionMethodSort cmsort = new CollectionMethodSort();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"Collectionc.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
        
        
    }//GEN-LAST:event_collectButActionPerformed

    private void ifbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifbutActionPerformed
        System.out.println("");
        IfStatement ifs = new IfStatement();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"IfStatement.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_ifbutActionPerformed

    private void switchstatebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchstatebutActionPerformed
        System.out.println("");
        SwitchStatement ss = new SwitchStatement();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"SwitchStatement.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_switchstatebutActionPerformed

    private void oVButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oVButActionPerformed
        System.out.println("");
        OverloadedMethod om= new OverloadedMethod();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"OverloadedMethod.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_oVButActionPerformed

    private void hashButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashButActionPerformed
        System.out.println("");
        Hashset hs = new Hashset();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"Hashset.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_hashButActionPerformed

    private void queButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queButActionPerformed
        System.out.println("");
        QueueMethods qm = new QueueMethods();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File((dpath+"QueueMethods.java"));
            try (Scanner zLoad = new Scanner(z)) {
                String buffer=""; // temp buffer for the while loop
                while(zLoad.hasNext()){
                    buffer += zLoad.nextLine() +"\n";
                }
                jTextArea1.setText(buffer);
            } // temp buffer for the while loop
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_queButActionPerformed

    private void trcabutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trcabutActionPerformed
        System.out.println("");
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);
        
            try {
            File z = new File(dpath+"TryCatch.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);
            TryCatch tc = new TryCatch();
            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
       
    }//GEN-LAST:event_trcabutActionPerformed

    private void sppButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sppButActionPerformed
        System.out.println("");
        StacksPushPop spp = new StacksPushPop();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"StacksPushPop.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_sppButActionPerformed

    private void atlButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atlButActionPerformed
        System.out.println("");
        Array2List a2L = new Array2List();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"Array2List.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
        
    }//GEN-LAST:event_atlButActionPerformed

    private void qualButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualButActionPerformed
        System.out.println("");
        EqualsMeth em = new EqualsMeth();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"EqualsMeth.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_qualButActionPerformed

    private void meventsButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meventsButActionPerformed
        System.out.println("");
        MouseEvent me = new MouseEvent();
	me.setSize(400,400);
        me.setVisible(true); 
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"MouseEvent.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_meventsButActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        JCheck go = new JCheck();
	go.setSize(300,200);
	go.setVisible(true);
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"JCheck.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
	 try {
        File myFile = new File(dpath + "imserver.jar");
        Desktop.getDesktop().open(myFile);
    } catch (IOException ex) {
        // no application registered 
    }
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"IMServer.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        ZeeEditorFrame ze=new ZeeEditorFrame();
        ze.setVisible(true);
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"ZeeEditorFrame.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        ColorChooser cc = new ColorChooser();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"ColorChooser.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void nestifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nestifActionPerformed
        System.out.println("");
        NestedIf ni=  new NestedIf();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"NestedIf.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_nestifActionPerformed

    private void genMButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genMButActionPerformed
        System.out.println("");
        GenericMethods gm = new GenericMethods();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"GenericMethods.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
        
    }//GEN-LAST:event_genMButActionPerformed

    private void genRetButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genRetButActionPerformed
        System.out.println("");
        GenericReturn gr = new GenericReturn();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"GenericReturn.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
        
    }//GEN-LAST:event_genRetButActionPerformed

    private void llbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llbutActionPerformed
        System.out.println("");
        LinkdList ll = new LinkdList();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"LinkdList.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
        
    }//GEN-LAST:event_llbutActionPerformed

    private void commonstringmethbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commonstringmethbutActionPerformed
        System.out.println("");
        CommonStringMethods csm = new CommonStringMethods();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"CommonStringMethods.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_commonstringmethbutActionPerformed

    private void enumButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enumButActionPerformed
        System.out.println("");
        System.out.println("NAME\tSIGN\tAGE");
            for(Enumeration people: Enumeration.values() ) 			
                System.out.printf("%s\t%s\t%s\n",people, people.getSign(), people.getAge());
            
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"Enumeration.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_enumButActionPerformed

    private void whilelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whilelpActionPerformed
        System.out.println("");
        WhileLoop wl = new WhileLoop();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"WhileLoop.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_whilelpActionPerformed

    private void forlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forlpActionPerformed
        System.out.println("");
        ForLoop fl = new ForLoop();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"ForLoop.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_forlpActionPerformed

    private void dwileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dwileActionPerformed
        System.out.println("");
        DoWhile dw= new DoWhile();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"DoWhile.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_dwileActionPerformed

    private void araybutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araybutActionPerformed
        System.out.println("");
        Arraysjava a = new Arraysjava();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"Arraysjava.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_araybutActionPerformed

    private void tastrngbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tastrngbutActionPerformed
        System.out.println("");
        DateToString toStringObject1 = new DateToString(8,5,1986);
            ToString toStringObject2 = new ToString("Kareem", toStringObject1);	
		System.out.println(toStringObject2);
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"ToString.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
                
                
    }//GEN-LAST:event_tastrngbutActionPerformed

    private void aLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLButtonActionPerformed
        System.out.println("");
        ArrayLists alst = new ArrayLists();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"ArrayLists.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_aLButtonActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        ComboBox cb = new ComboBox();
        cb.setSize(300,200);
        cb.setVisible(true); 
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"ComboBox.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        RadioButton rb = new RadioButton();
	rb.setSize(300,200);
	rb.setVisible(true);
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"RadioButton.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        JayList jl = new JayList();
        jl.setSize(300,200);
	jl.setVisible(true);
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"JayList.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        MultiSelectList kz = new MultiSelectList();
	kz.setSize(400,400);
	kz.setVisible(true);
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"MultiSelectList.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void recurButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recurButActionPerformed
        System.out.println("");
        Recursion recur = new Recursion();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"Recursion.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_recurButActionPerformed

    private void mouseAButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouseAButActionPerformed
        MouseAdapterC mac = new MouseAdapterC();
	mac.setSize(400,400);
        mac.setVisible(true);
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"MouseAdapterC.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_mouseAButActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        GooeyEvent pretty = new GooeyEvent();
        pretty.setSize(350, 200);										//sets window size
	pretty.setVisible(true);
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"GooeyEvent.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"Gooeysumof2.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
         Gooeysumof2 gs = new Gooeysumof2();
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        GooeyJFrame kareem = new GooeyJFrame();		
        kareem.setSize(375,180);											//set window size
	kareem.setVisible(true);
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"GooeyJFrame.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton31ActionPerformed

    private void fileButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButActionPerformed
        final Formatter fc;
		
		
		try{
			fc = new Formatter("kza.txt");
			System.out.println("you created the file kza.txt");
		}
			
		catch(Exception e){
			System.out.println("Error");
		}	
        File x = new File ("kza.txt");
		
		if(x.exists())
			System.out.println(x.getName()+ " exists!");
		else
			System.out.println("this file doesn't exists!");
      
        FilesWriteClass3 kz2 = new FilesWriteClass3();
		kz2.openFile();
		kz2.addRecords();
		kz2.closeFile();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"FileIO.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_fileButActionPerformed

    private void enhancedbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enhancedbutActionPerformed
        System.out.println("");
        EnhancedFor ef = new EnhancedFor();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"EnhancedFor.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
        
    }//GEN-LAST:event_enhancedbutActionPerformed

    private void multiDButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiDButActionPerformed
        System.out.println("");
        multiDArray mda = new multiDArray();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File((dpath+"multiDarray.java"));
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
        
    }//GEN-LAST:event_multiDButActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        System.out.println("");
        ArrayTable at = new ArrayTable();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File((dpath+"ArrayTable.java"));
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton43ActionPerformed

    private void ranButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ranButActionPerformed
        System.out.println("");
        Randomnumbers rn = new Randomnumbers();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File((dpath+"Randomnumbers.java"));
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
        
    }//GEN-LAST:event_ranButActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
       if (Desktop.isDesktopSupported()) {
    try {
        File myFile = new File(dpath + "Java an Intro to problem solving and programming 6th edition.pdf");
        Desktop.getDesktop().open(myFile);
    } catch (IOException ex) {
        // no application registered for PDFs
    }
}
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        Thread t1 = new Thread(new ThreadsIntro("one"));
	Thread t2 = new Thread(new ThreadsIntro("two"));
	Thread t3 = new Thread(new ThreadsIntro("three"));
        Thread t4 = new Thread(new ThreadsIntro("Four"));
	t1.start();
	t2.start();
        t3.start();
	t4.start();

        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File((dpath+"ThreadsIntro.java"));
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
         if (Desktop.isDesktopSupported()) {
    try {
        File myFile = new File(dpath + "imserver.jar");
        Desktop.getDesktop().open(myFile);
    } catch (IOException ex) {
        // no application registered for PDFs
    } try {
        File myFile = new File(dpath + "imclient.jar");
        Desktop.getDesktop().open(myFile);
    } catch (IOException ex) {
        // no application registered for PDFs
    }
    }//GEN-LAST:event_jButton54ActionPerformed
    }
    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
         try {
        File myFile = new File(dpath + "imclient.jar");
        Desktop.getDesktop().open(myFile);
    } catch (IOException ex) {
     
    }			 
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"IMClient.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        bBrowser browse =new bBrowser();
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);

        try {
            File z = new File(dpath+"bBrowser.java");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_jButton59ActionPerformed

    private void readMeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readMeButActionPerformed
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,0,800,600);
        try {
            File z = new File(dpath+"README.TXT");
            Scanner zLoad = new Scanner(z);
            String buffer=""; // temp buffer for the while loop
            while(zLoad.hasNext()){
                buffer += zLoad.nextLine() +"\n";
            }
            jTextArea1.setText(buffer);

            zLoad.close();
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not Found");
        }
    }//GEN-LAST:event_readMeButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aLButton;
    private javax.swing.JButton araybut;
    private javax.swing.JButton atlBut;
    private javax.swing.JButton collectBut;
    private javax.swing.JButton commonstringmethbut;
    private javax.swing.JButton dwile;
    private javax.swing.JButton enhancedbut;
    private javax.swing.JButton enumBut;
    private javax.swing.JButton fileBut;
    private javax.swing.JButton forlp;
    private javax.swing.JButton genMBut;
    private javax.swing.JButton genRetBut;
    private javax.swing.JButton hashBut;
    private javax.swing.JButton ifbut;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton59;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton llbut;
    private javax.swing.JButton meventsBut;
    private javax.swing.JButton mouseABut;
    private javax.swing.JButton multiDBut;
    private javax.swing.JButton nestif;
    private javax.swing.JButton oVBut;
    private javax.swing.JButton qualBut;
    private javax.swing.JButton queBut;
    private javax.swing.JButton ranBut;
    private javax.swing.JButton readMeBut;
    private javax.swing.JButton recurBut;
    private javax.swing.JButton sppBut;
    private javax.swing.JButton switchstatebut;
    private javax.swing.JButton tastrngbut;
    private javax.swing.JButton trcabut;
    private javax.swing.JButton whilelp;
    // End of variables declaration//GEN-END:variables
}
